### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [iv522-sibsutis/unit-converter#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/iv522-sibsutis/unit-converter/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/iv522-sibsutis/unit-converter/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by danil10171** [comment]
Данный продукт конвертирует такие величины как : вес, длина, объем, температуру, так же можно добавить перевод валют в зависиммости от нынешнего курса.

Входные данными служат положительные целые числа.

Приложение будет консольным. Входные данные должны быть в следующем порядке: 
1)Величина(вес, длина, объем, и тд.);
2)число;
3)из чего перевести;
4)во что превести;

На выход поступает отконвертированная величина.

**Comment by evgeny-p** [comment]
1. ТЗ состоит из двух строчек, не содержащих практически никакой информации о приложении. Часть информации, которая была бы уместна в ТЗ, почему-то написана в комментариях к задаче.
2. > Входные данные должны быть в следующем порядке: 
   > 1)Величина(вес, длина, объем, и тд.);
   > 
   > 2)число;
   > 
   > 3)из чего перевести;
   > 
   > 4)во что превести;
   
   Посмотрите описание использования консольных утилит на любой man-странице.
   
   Некоторые примеры:
   - [ls](http://linux.die.net/man/1/ls)
   - [grep](http://linux.die.net/man/1/grep)
   - [git clone](https://git-scm.com/docs/git-clone)
   
   Текущее описание даже не дает представления: будет приложение работать в интерактивном режиме или нет. Есть предложение реализовать оба режима. И это тоже нужно отразить в ТЗ. Помимо общего описания (см. примеры мануалов) можно писать примеры сессий использования приложения. В случае консольных приложений без псевдографики это несложно.
3. Где и как хранятся данные, необходимые для перевода величин? Поддерживаемые величины, коэффициенты. Это во многом определит реализацию алгоритма перевода.

**Comment by danil10171** [comment]
ТЗ переделано.Что можно добавить?

**Comment by evgeny-p** [comment]
> Данные для перевода величин будут храниться в отдельном файле формата ".с"

Что есть «формат “.c”»? Предположительно, подразумевалось расширение файла. Возникает вопрос: почему файл, содержащий список величин в указанном далее формате, имеет расширение, характерное для файлов исходного кода на языке C?

Переходите к декомпозиции проекта на задачи. Возможно, в процессе их составления потребуется уточнить ТЗ.

Обращаю внимание, что задача не паралеллится по типам переводимых величин, т.к. фактически алгоритм перевода общий для всех. В процессе подготовки задач подумайте, какие алгоритмы и структуры данных будут удобны для реализации.

**Comment by danil10171** [comment]
Разбили проект на задачи, поменяли расширение файла в ТЗ.

**Comment by evgeny-p** [comment]
1. Почему предполагается, что весь код приложения будет в единственном файле `main.c`?
2. Не проработан алгоритм перевода. Попробуйте написать простой пример входного файла для перевода длин в следующих единицах: сантиметры, метры, километры. Какие правила будут храниться в нем? Как, используя их, будет выполняться перевод? Какая структура данных будет выбрана для хранения правил в памяти? Текущее ТЗ никак не проясняет реализацию. Плюс, предполагается, что вся реализация будет выполнена в рамках одной задачи.

**Comment by evgeny-p** [comment]
Ключевые вопросы обсудили на паре, в формат файла с правилами перевода внесены изменения.
